/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
import controllers.*;
import models.*;
import javax.swing.DefaultListModel;
import com.sun.speech.freetts.*;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author DHT
 */
public class DictionaryApplication extends javax.swing.JFrame {

    /**
     * Creates new form DictionaryApplication
     */
    DictionaryCommandLine DC = new DictionaryCommandLine();
    public DictionaryApplication() {
        initComponents();
        //Load dữ liệu:
        try {
            
            DC.insertFromFile();
            var dataListWord = new DefaultListModel<String>();
            for(Word i : DC.getListWord()){
                dataListWord.addElement(i.getWordTarget());
            }
            lst_listWord.setModel(dataListWord);
            
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSMTextFullBeanInfo1 = new rojeru_san.RSMTextFullBeanInfo();
        rSPanelGradiente1 = new rspanelgradiente.RSPanelGradiente();
        rSButtonIconI8 = new rojerusan.RSButtonIconI();
        rSButtonIconI9 = new rojerusan.RSButtonIconI();
        rSButtonIconI10 = new rojerusan.RSButtonIconI();
        rSPanelGradiente2 = new rspanelgradiente.RSPanelGradiente();
        rSPanelImage2 = new rojerusan.RSPanelImage();
        rSPanelGradiente3 = new rspanelgradiente.RSPanelGradiente();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_listWord = new javax.swing.JList<>();
        btn_searchText = new rojeru_san.RSButton();
        txt_TextTranslate = new rojeru_san.RSMTextFull();
        btn_Speaking = new rojerusan.RSButtonIconI();
        checkbox_useApi = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Mean = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần mềm từ điển - Đỗ Hữu Toàn Colab Lê Đình Thiệu");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1205, 750));
        setMinimumSize(new java.awt.Dimension(1205, 750));
        getContentPane().setLayout(null);

        rSPanelGradiente1.setBackground(new java.awt.Color(48, 63, 159));
        rSPanelGradiente1.setColorPrimario(new java.awt.Color(42, 49, 64));
        rSPanelGradiente1.setColorSecundario(new java.awt.Color(42, 49, 64));

        rSButtonIconI8.setBackground(new java.awt.Color(42, 49, 64));
        rSButtonIconI8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/baseline_add_white_18dp.png"))); // NOI18N
        rSButtonIconI8.setColorHover(new java.awt.Color(57, 67, 87));
        rSButtonIconI8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rSButtonIconI8.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        rSButtonIconI8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI8ActionPerformed(evt);
            }
        });

        rSButtonIconI9.setBackground(new java.awt.Color(42, 49, 64));
        rSButtonIconI9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/baseline_create_white_18dp.png"))); // NOI18N
        rSButtonIconI9.setColorHover(new java.awt.Color(57, 67, 87));
        rSButtonIconI9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rSButtonIconI9.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        rSButtonIconI9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI9ActionPerformed(evt);
            }
        });

        rSButtonIconI10.setBackground(new java.awt.Color(42, 49, 64));
        rSButtonIconI10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/baseline_search_white_18dp.png"))); // NOI18N
        rSButtonIconI10.setColorHover(new java.awt.Color(57, 67, 87));
        rSButtonIconI10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rSButtonIconI10.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        rSButtonIconI10.setSelected(true);
        rSButtonIconI10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rSPanelGradiente1Layout = new javax.swing.GroupLayout(rSPanelGradiente1);
        rSPanelGradiente1.setLayout(rSPanelGradiente1Layout);
        rSPanelGradiente1Layout.setHorizontalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSButtonIconI9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(rSButtonIconI8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(rSButtonIconI10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        rSPanelGradiente1Layout.setVerticalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(rSButtonIconI10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonIconI8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonIconI9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(498, Short.MAX_VALUE))
        );

        getContentPane().add(rSPanelGradiente1);
        rSPanelGradiente1.setBounds(0, 80, 60, 630);

        rSPanelGradiente2.setColorPrimario(new java.awt.Color(42, 49, 64));
        rSPanelGradiente2.setColorSecundario(new java.awt.Color(42, 49, 64));

        rSPanelImage2.setImagen(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage2Layout = new javax.swing.GroupLayout(rSPanelImage2);
        rSPanelImage2.setLayout(rSPanelImage2Layout);
        rSPanelImage2Layout.setHorizontalGroup(
            rSPanelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );
        rSPanelImage2Layout.setVerticalGroup(
            rSPanelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout rSPanelGradiente2Layout = new javax.swing.GroupLayout(rSPanelGradiente2);
        rSPanelGradiente2.setLayout(rSPanelGradiente2Layout);
        rSPanelGradiente2Layout.setHorizontalGroup(
            rSPanelGradiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente2Layout.createSequentialGroup()
                .addContainerGap(1107, Short.MAX_VALUE)
                .addComponent(rSPanelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        rSPanelGradiente2Layout.setVerticalGroup(
            rSPanelGradiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelGradiente2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(rSPanelGradiente2);
        rSPanelGradiente2.setBounds(0, 0, 1193, 86);

        rSPanelGradiente3.setToolTipText("");
        rSPanelGradiente3.setColorPrimario(new java.awt.Color(255, 255, 255));
        rSPanelGradiente3.setColorSecundario(new java.awt.Color(255, 255, 255));
        rSPanelGradiente3.setLayout(null);

        lst_listWord.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        lst_listWord.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lst_listWord.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lst_listWord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lst_listWord.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lst_listWordValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lst_listWord);

        rSPanelGradiente3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 105, 491, 403);

        btn_searchText.setText("Dịch");
        btn_searchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchTextActionPerformed(evt);
            }
        });
        rSPanelGradiente3.add(btn_searchText);
        btn_searchText.setBounds(377, 11, 136, 29);

        txt_TextTranslate.setPlaceholder("Gõ văn bản cần dịch");
        rSPanelGradiente3.add(txt_TextTranslate);
        txt_TextTranslate.setBounds(10, 11, 353, 40);

        btn_Speaking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/speaking.png"))); // NOI18N
        btn_Speaking.setText("Phát âm");
        btn_Speaking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Speaking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SpeakingActionPerformed(evt);
            }
        });
        rSPanelGradiente3.add(btn_Speaking);
        btn_Speaking.setBounds(324, 519, 177, 40);

        checkbox_useApi.setText("Sử dụng API để dịch văn bản?");
        rSPanelGradiente3.add(checkbox_useApi);
        checkbox_useApi.setBounds(340, 60, 169, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        rSPanelGradiente3.add(jComboBox1);
        jComboBox1.setBounds(100, 70, 132, 20);

        jLabel1.setText("Chọn ngôn ngữ: ");
        rSPanelGradiente3.add(jLabel1);
        jLabel1.setBounds(20, 70, 81, 20);

        getContentPane().add(rSPanelGradiente3);
        rSPanelGradiente3.setBounds(70, 110, 530, 570);

        txt_Mean.setEditable(false);
        txt_Mean.setBorder(null);
        txt_Mean.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(txt_Mean);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(620, 110, 550, 570);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonIconI8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonIconI8ActionPerformed

    private void rSButtonIconI9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonIconI9ActionPerformed

    private void rSButtonIconI10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonIconI10ActionPerformed

    private void lst_listWordValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lst_listWordValueChanged
        // TODO add your handling code here:
        String searchWord = lst_listWord.getSelectedValue();
        String content = DC.dictionaryLookup(searchWord);
        txt_Mean.setText(content);
    }//GEN-LAST:event_lst_listWordValueChanged

    //Bắt sự kiện button đọc từ
    private void btn_SpeakingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SpeakingActionPerformed
        // TODO add your handling code here:
        System.setProperty("freetts.voices", "com.sun.speech.freetts.en.us.cmu_us_kal.KevinVoiceDirectory");
        Voice voice = VoiceManager.getInstance().getVoice("kevin16");
        if(voice!=null){
            voice.allocate();
            voice.speak(lst_listWord.getSelectedValue());
        }
    }//GEN-LAST:event_btn_SpeakingActionPerformed
    
    //Get dữ liệu từ API:
    
    private String sendHttpGETRequest(String url_get) throws IOException {
        URL obj = new URL(url_get);
        HttpURLConnection httpURLConnection = (HttpURLConnection) obj.openConnection();
        httpURLConnection.setRequestMethod("GET");
        httpURLConnection.setRequestProperty("User-Agent", "Mozilla/5.0");
        int responseCode = httpURLConnection.getResponseCode();
        System.out.println("GET Response Code :: " + responseCode);
        if (responseCode == HttpURLConnection.HTTP_OK) { // success
            BufferedReader in = new BufferedReader(new InputStreamReader(httpURLConnection.getInputStream()));
            String inputLine;
            StringBuffer response = new StringBuffer();

            while ((inputLine = in .readLine()) != null) {
                response.append(inputLine);
            } in .close();

            // print result
            System.out.println(response.toString());
            return response.toString();
        } else {
            System.out.println("GET request not worked");
            String res = "Not found 404";
            return res;
        }
        
        
        /*
        for (int i = 1; i <= 8; i++) {
            System.out.println(httpURLConnection.getHeaderFieldKey(i) + " = " + httpURLConnection.getHeaderField(i));
        }
        */

    }
    
    
    
    private void btn_searchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchTextActionPerformed
        // TODO add your handling code here:
        if(checkbox_useApi.getSelectedObjects() != null){
            String path = "https://dht-translate-api.herokuapp.com/api/" + txt_TextTranslate.getText().replace(" ", "%20").replace("?", "%3F");
            
            try {
                txt_Mean.setText(sendHttpGETRequest(path));
            } catch (IOException ex) {
                txt_Mean.setText("Không kết nối được đến api ! Kiểm tra lại kết nối internet");
            }
        }
            
    }//GEN-LAST:event_btn_searchTextActionPerformed

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                System.out.println(info.getName());
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DictionaryApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonIconI btn_Speaking;
    private rojeru_san.RSButton btn_searchText;
    private javax.swing.JCheckBox checkbox_useApi;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lst_listWord;
    private rojerusan.RSButtonIconI rSButtonIconI10;
    private rojerusan.RSButtonIconI rSButtonIconI8;
    private rojerusan.RSButtonIconI rSButtonIconI9;
    private rojeru_san.RSMTextFullBeanInfo rSMTextFullBeanInfo1;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente1;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente2;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente3;
    private rojerusan.RSPanelImage rSPanelImage2;
    private javax.swing.JTextPane txt_Mean;
    private rojeru_san.RSMTextFull txt_TextTranslate;
    // End of variables declaration//GEN-END:variables
}
