/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
import controllers.*;
import models.*;
import javax.swing.DefaultListModel;
import com.sun.speech.freetts.*;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.UnsupportedEncodingException;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;

import java.net.URLEncoder;
import java.util.ArrayList;
/**
 *
 * @author DHT
 */
public class DictionaryApplication extends javax.swing.JFrame {

    /**
     * Creates new form DictionaryApplication
     */
    DictionaryCommandLine DC = new DictionaryCommandLine();
    searchPanel formSearch;
    public DictionaryApplication() {
        initComponents();
        
        //Load dữ liệu:
        
        try {
            
            DC.insertFromFile();
         
        } catch (IOException e) {
            System.err.println(e.getMessage());
        }
        
        formSearch = new searchPanel(DC);
        panelShow.add(formSearch);
        formSearch.setVisible(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSMTextFullBeanInfo1 = new rojeru_san.RSMTextFullBeanInfo();
        rSPanelGradiente1 = new rspanelgradiente.RSPanelGradiente();
        rSButtonIconI8 = new rojerusan.RSButtonIconI();
        rSButtonIconI9 = new rojerusan.RSButtonIconI();
        rSButtonIconI10 = new rojerusan.RSButtonIconI();
        rSPanelGradiente2 = new rspanelgradiente.RSPanelGradiente();
        rSPanelImage2 = new rojerusan.RSPanelImage();
        panelShow = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần mềm từ điển - Đỗ Hữu Toàn Colab Lê Đình Thiệu");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1205, 750));
        setMinimumSize(new java.awt.Dimension(1205, 750));
        getContentPane().setLayout(null);

        rSPanelGradiente1.setBackground(new java.awt.Color(48, 63, 159));
        rSPanelGradiente1.setColorPrimario(new java.awt.Color(42, 49, 64));
        rSPanelGradiente1.setColorSecundario(new java.awt.Color(42, 49, 64));

        rSButtonIconI8.setBackground(new java.awt.Color(42, 49, 64));
        rSButtonIconI8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/baseline_add_white_18dp.png"))); // NOI18N
        rSButtonIconI8.setColorHover(new java.awt.Color(57, 67, 87));
        rSButtonIconI8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rSButtonIconI8.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        rSButtonIconI8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI8ActionPerformed(evt);
            }
        });

        rSButtonIconI9.setBackground(new java.awt.Color(42, 49, 64));
        rSButtonIconI9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/baseline_create_white_18dp.png"))); // NOI18N
        rSButtonIconI9.setColorHover(new java.awt.Color(57, 67, 87));
        rSButtonIconI9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rSButtonIconI9.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        rSButtonIconI9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI9ActionPerformed(evt);
            }
        });

        rSButtonIconI10.setBackground(new java.awt.Color(42, 49, 64));
        rSButtonIconI10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/baseline_search_white_18dp.png"))); // NOI18N
        rSButtonIconI10.setColorHover(new java.awt.Color(57, 67, 87));
        rSButtonIconI10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rSButtonIconI10.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        rSButtonIconI10.setSelected(true);
        rSButtonIconI10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rSPanelGradiente1Layout = new javax.swing.GroupLayout(rSPanelGradiente1);
        rSPanelGradiente1.setLayout(rSPanelGradiente1Layout);
        rSPanelGradiente1Layout.setHorizontalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSButtonIconI9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(rSButtonIconI8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(rSButtonIconI10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        rSPanelGradiente1Layout.setVerticalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(rSButtonIconI10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonIconI8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonIconI9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(498, Short.MAX_VALUE))
        );

        getContentPane().add(rSPanelGradiente1);
        rSPanelGradiente1.setBounds(0, 80, 60, 630);

        rSPanelGradiente2.setColorPrimario(new java.awt.Color(42, 49, 64));
        rSPanelGradiente2.setColorSecundario(new java.awt.Color(42, 49, 64));

        rSPanelImage2.setImagen(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage2Layout = new javax.swing.GroupLayout(rSPanelImage2);
        rSPanelImage2.setLayout(rSPanelImage2Layout);
        rSPanelImage2Layout.setHorizontalGroup(
            rSPanelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );
        rSPanelImage2Layout.setVerticalGroup(
            rSPanelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout rSPanelGradiente2Layout = new javax.swing.GroupLayout(rSPanelGradiente2);
        rSPanelGradiente2.setLayout(rSPanelGradiente2Layout);
        rSPanelGradiente2Layout.setHorizontalGroup(
            rSPanelGradiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente2Layout.createSequentialGroup()
                .addContainerGap(1087, Short.MAX_VALUE)
                .addComponent(rSPanelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        rSPanelGradiente2Layout.setVerticalGroup(
            rSPanelGradiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelGradiente2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(rSPanelGradiente2);
        rSPanelGradiente2.setBounds(0, 0, 1220, 86);

        panelShow.setMinimumSize(new java.awt.Dimension(1146, 610));
        panelShow.setPreferredSize(new java.awt.Dimension(1108, 592));

        javax.swing.GroupLayout panelShowLayout = new javax.swing.GroupLayout(panelShow);
        panelShow.setLayout(panelShowLayout);
        panelShowLayout.setHorizontalGroup(
            panelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1146, Short.MAX_VALUE)
        );
        panelShowLayout.setVerticalGroup(
            panelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        getContentPane().add(panelShow);
        panelShow.setBounds(80, 100, 1098, 570);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonIconI8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI8ActionPerformed
        // TODO add your handling code here:
        formSearch.setVisible(false);
    }//GEN-LAST:event_rSButtonIconI8ActionPerformed

    private void rSButtonIconI9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonIconI9ActionPerformed

    private void rSButtonIconI10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI10ActionPerformed
        // TODO add your handling code here:
        formSearch.setVisible(true);
    }//GEN-LAST:event_rSButtonIconI10ActionPerformed

   
    //Get dữ liệu từ API:
    
    private String sendHttpGETRequest(String url_get) throws IOException {
        URL obj = new URL(url_get);
        HttpURLConnection httpURLConnection = (HttpURLConnection) obj.openConnection();
        httpURLConnection.setRequestMethod("GET");
        httpURLConnection.setRequestProperty("User-Agent", "Mozilla/5.0");
        int responseCode = httpURLConnection.getResponseCode();
        System.out.println("GET Response Code :: " + responseCode);
        if (responseCode == HttpURLConnection.HTTP_OK) { // success
            BufferedReader in = new BufferedReader(new InputStreamReader(httpURLConnection.getInputStream()));
            String inputLine;
            StringBuffer response = new StringBuffer();

            while ((inputLine = in .readLine()) != null) {
                response.append(inputLine);
            } in .close();

            // print result
            System.out.println(response.toString());
            return response.toString();
        } else {
            System.out.println("GET request not worked");
            String res = "Not found 404";
            return res;
        }
        
        
        /*
        for (int i = 1; i <= 8; i++) {
            System.out.println(httpURLConnection.getHeaderFieldKey(i) + " = " + httpURLConnection.getHeaderField(i));
        }
        */

    }
    
    
    
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                System.out.println(info.getName());
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DictionaryApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelShow;
    private rojerusan.RSButtonIconI rSButtonIconI10;
    private rojerusan.RSButtonIconI rSButtonIconI8;
    private rojerusan.RSButtonIconI rSButtonIconI9;
    private rojeru_san.RSMTextFullBeanInfo rSMTextFullBeanInfo1;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente1;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente2;
    private rojerusan.RSPanelImage rSPanelImage2;
    // End of variables declaration//GEN-END:variables
}
